version: '3.8'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: 'http://localhost:3000'
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./www:/var/www/certbot
    depends_on:
      - nextjs-app
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./www:/var/www/certbot
    environment:
      - CERTBOT_EMAIL=youremail@example.com
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot >> /var/log/certbot.log 2>&1 && nginx -s reload; sleep 12h & wait $${!}; done;'"
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
