import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata = {
	title: 'Технобар',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='ru'>
			<body
				className={`${geistSans.variable} ${geistMono.variable}`}
				style={{
					display: 'flex',
					flexDirection: 'column',
					justifyContent: 'space-between',
					minHeight: '100vh',
				}}
			>
				<div style={{ flexGrow: 1 }}>{children}</div>
			</body>
		</html>
	)
}
